### ISSUE TITLE
AnimRoundTypes documentation seems off.

### ISSUE THREAD

**Issue by Benst1996** [StanHash/DOC#2]
https://github.com/StanHash/DOC/blob/de69d185c39c3d654f0b07784b20ea0309ca7fbc/BattleAnims/AnimRoundTypes.txt#L74

I actually think byte 2 flag 0x80 indicates end battle. It's checked at 0x5882E in FE8U to end a loop. Also checked at 0x7A8A6 to determine whether map battle has ended.

I also think byte 2 flag 0x40 indicates that the Target/Defender is attacking in this round. It's checked against [0x203E108] (which indicates whether the initiator is left or right) at 0x5836E in FE8U to figure out whether the left side or right side is attacking.

**Comment by StanHash** [comment]
That's taken from the Teq Doq so blame Teq. I changed it to have the names of the constants I use in decomp, which should be more complete and accurate.
